/* AUTO-COPIED FROM THE SERVER. Do not edit this file in the client project.
   Change it in mongo-explorer-server/src/model/shared-models/ and run
   scripts/sync-shared-models.ts. */

import { ObjectId } from 'mongodb';
import { CollectionRef, ExplainResult } from './explorer.model';
import { FieldDescriptor } from './bson-type.model';

/**
 * One stage of an aggregation pipeline in the builder. Stages are addressable so
 * that editing stage four leaves the user's work on stages one to three intact.
 */
export interface PipelineStage {
    /** Stable identifier, so edits and previews survive reordering. */
    id: string;

    /** Operator name including the dollar sign, for example '$match'. */
    operator: string;

    /** Stage body as Extended JSON text — the user's literal input. */
    body: string;

    /** Disabled stages are skipped during execution but retained in the list. */
    isEnabled: boolean;

    /** Free-text note, saved alongside the pipeline. */
    comment?: string;
}

/** Full aggregation builder state, mirrored into the MCP session state. */
export interface PipelineBuilderState extends CollectionRef {
    /** The stages, in execution order. */
    stages: PipelineStage[];

    /** Whether the user is editing structured stages or raw text. */
    mode: 'stages' | 'text';

    /** True when the pipeline contains a write stage such as $out or $merge. */
    hasWriteStage: boolean;

    /** Names of any write stages present, for display in the warning. */
    writeStages: string[];

    /** True when the pipeline has unsaved changes. */
    isDirty: boolean;

    /** Identifier of the saved pipeline this was loaded from, when any. */
    savedPipelineId?: ObjectId;
}

/** Request to run or preview an aggregation pipeline. */
export interface PipelineRunRequest extends CollectionRef {
    /** The stages to execute. Disabled stages are expected to be filtered out. */
    stages: PipelineStage[];

    /**
     * Execute only the prefix up to and including this stage index. Absent means
     * the whole pipeline. This is how a pipeline is debugged.
     */
    upToStageIndex?: number;

    /** Preview sample size. Applied as a trailing limit. */
    sampleSize: number;

    /** Time budget in milliseconds, clamped server-side. */
    maxTimeMs?: number;
}

/**
 * Result of a pipeline preview. Always labelled as a preview: a preview count is
 * never a result count.
 */
export interface PipelinePreviewResult {
    /** Resulting documents as Extended JSON. */
    documentsJson: string;

    /** How many documents came back. */
    returnedCount: number;

    /** The sample size that was applied. */
    appliedSampleSize: number;

    /** Always true — this endpoint never returns a complete result set. */
    isPreview: true;

    /** True when the sample limit or time limit truncated the output. */
    isPartial: boolean;

    /** Index of the last stage that was executed. */
    lastStageIndex: number;

    /** Wall-clock duration in milliseconds. */
    durationMs: number;

    /** Fields observed in the output, for column derivation. */
    fields: FieldDescriptor[];
}

/** Explain output for a pipeline. */
export interface PipelineExplainResult extends ExplainResult {
    /** Per-stage notes extracted from the plan, when available. */
    stageNotes: PipelineStageNote[];
}

/** An observation about one stage of an explained pipeline. */
export interface PipelineStageNote {
    /** Index of the stage in the submitted pipeline. */
    stageIndex: number;

    /** Operator name. */
    operator: string;

    /** Whether this stage was able to use an index. */
    usesIndex: boolean;

    /** Plain-language note about the stage's execution. */
    note?: string;
}

/** A pipeline saved to the Application Database for reuse. */
export interface SavedPipeline {
    /** Identifier in the Application Database. */
    _id: ObjectId;

    /** User-supplied name. */
    name: string;

    /** Optional description. */
    description?: string;

    /** Connection this pipeline was authored against. */
    connectionId: ObjectId;

    /** Target Database name. */
    databaseName: string;

    /** Collection name. */
    collectionName: string;

    /** The stages. */
    stages: PipelineStage[];

    /** When the pipeline was created, as an ISO-8601 string. */
    createdAt: string;

    /** When the pipeline was last updated, as an ISO-8601 string. */
    updatedAt: string;
}

/** Languages the builder can export a pipeline into. */
export type PipelineExportLanguage = 'node' | 'mongosh' | 'python' | 'json';

/** Generated code for a pipeline. */
export interface PipelineExportResult {
    /** Which language was generated. */
    language: PipelineExportLanguage;

    /** The generated source text. */
    code: string;
}

/**
 * Aggregation stages that write to a collection. A pipeline containing one of
 * these is a data mutation wearing read-only clothing, and is the most likely
 * way the safety model gets circumvented by accident.
 */
export const WRITE_PIPELINE_STAGES: readonly string[] = ['$out', '$merge'];
