/* AUTO-COPIED FROM THE SERVER. Do not edit this file in the client project.
   Change it in mongo-explorer-server/src/model/shared-models/ and run
   scripts/sync-shared-models.ts. */

import { ObjectId } from 'mongodb';
import { AzureOidcFlow, ConnectionStrategyKind } from './connection-strategy-kind.model';

/**
 * A persisted, user-visible Target Database connection configuration. Secrets are
 * encrypted at rest and are never returned to the client.
 */
export interface SavedConnection {
    /** Identifier in the Application Database. */
    _id: ObjectId;

    /** User-supplied display name. */
    name: string;

    /** Which authentication mechanism this connection uses. */
    strategyKind: ConnectionStrategyKind;

    /**
     * Guard rail preventing every write through this connection. Enforced
     * server-side, not merely hidden in the interface.
     */
    isReadOnly: boolean;

    /** Optional free-text note shown in the connection list. */
    notes?: string;

    /** Colour token used to tint the interface while this connection is active. */
    colorTag?: string;

    /** Strategy-specific configuration. Exactly one member is populated. */
    config: ConnectionConfig;

    /** When the connection was created, as an ISO-8601 string. */
    createdAt: string;

    /** When the connection was last successfully opened, as an ISO-8601 string. */
    lastConnectedAt?: string;
}

/** Strategy-specific configuration, discriminated by the owning strategy kind. */
export interface ConnectionConfig {
    /** Populated when strategyKind is ConnectionString. */
    connectionString?: ConnectionStringConfig;

    /** Populated when strategyKind is Scram. */
    scram?: ScramConfig;

    /** Populated when strategyKind is AzureOidc. */
    azureOidc?: AzureOidcConfig;

    /** Populated when strategyKind is X509. */
    x509?: X509Config;

    /** Transport options applied on top of any strategy. */
    transport?: TransportOptions;
}

/** Configuration for a hand-written connection URI. */
export interface ConnectionStringConfig {
    /** The full mongodb:// or mongodb+srv:// URI. May embed credentials. */
    uri: string;

    /** Default database to open after connecting. */
    defaultDatabase?: string;
}

/** Configuration for username and password authentication. */
export interface ScramConfig {
    /** Host name of the deployment. */
    host: string;

    /** Port the deployment listens on. */
    port: number;

    /** Login name. */
    userName: string;

    /** Whether a password has been stored for this connection. */
    hasStoredPassword: boolean;

    /** Database holding the user credentials. */
    authSource?: string;

    /** Replica set name, when connecting to a set directly. */
    replicaSet?: string;

    /** Default database to open after connecting. */
    defaultDatabase?: string;
}

/**
 * Configuration for Microsoft Entra ID authentication against Azure Cosmos DB
 * for MongoDB (vCore). See workspace/research/azure-vcore-oidc.md — several of
 * these values are unverified hypotheses until tested against a real cluster.
 */
export interface AzureOidcConfig {
    /** Cluster host, typically <cluster>.mongocluster.cosmos.azure.com. */
    host: string;

    /** Port the cluster listens on. */
    port: number;

    /** Entra ID directory (tenant) identifier. */
    tenantId: string;

    /** Application (client) identifier registered in the tenant. */
    clientId: string;

    /** How the access token is obtained. */
    flow: AzureOidcFlow;

    /**
     * Token audience or scope. The correct value is unverified; candidates are
     * documented in the research notes. Never guessed at runtime.
     */
    tokenResource: string;

    /**
     * Driver host allow-list for OIDC. Must be set explicitly — the driver's
     * default covers only MongoDB's own domains, which is the leading suspect
     * for why OIDC fails against Azure vCore.
     */
    allowedHosts: string[];

    /** Principal name sent as the connection user, when the cluster requires one. */
    principalName?: string;

    /** Whether a client secret has been stored, for the client-credentials flow. */
    hasStoredClientSecret: boolean;

    /** Managed identity client id, for a user-assigned identity. */
    managedIdentityClientId?: string;

    /** Default database to open after connecting. */
    defaultDatabase?: string;
}

/** Configuration for TLS client certificate authentication. */
export interface X509Config {
    /** Host name of the deployment. */
    host: string;

    /** Port the deployment listens on. */
    port: number;

    /** Absolute path to the combined certificate and key file. */
    certificateKeyFilePath: string;

    /** Whether a passphrase has been stored for the key file. */
    hasStoredPassphrase: boolean;

    /** Default database to open after connecting. */
    defaultDatabase?: string;
}

/** Transport-level options layered over any strategy. */
export interface TransportOptions {
    /** Whether TLS is required. */
    useTls?: boolean;

    /** Absolute path to a certificate authority bundle. */
    tlsCaFilePath?: string;

    /**
     * Disables certificate validation. Dangerous, and surfaced in the interface
     * with a loud warning.
     */
    tlsAllowInvalidCertificates?: boolean;

    /** Whether retryable writes are enabled. */
    retryWrites?: boolean;

    /** Server selection timeout, in milliseconds. */
    serverSelectionTimeoutMs?: number;
}

/**
 * The redacted form of a connection returned to the client. Secrets are absent
 * by construction: the builder never receives them.
 */
export interface SavedConnectionListing {
    /** Identifier in the Application Database. */
    _id: ObjectId;

    /** User-supplied display name. */
    name: string;

    /** Which authentication mechanism this connection uses. */
    strategyKind: ConnectionStrategyKind;

    /** Guard rail preventing every write through this connection. */
    isReadOnly: boolean;

    /** Host and port summary, suitable for display. */
    endpointSummary: string;

    /** Optional free-text note. */
    notes?: string;

    /** Colour token used to tint the interface. */
    colorTag?: string;

    /** When the connection was last successfully opened. */
    lastConnectedAt?: string;

    /** True when this connection points at the Application Database itself. */
    isApplicationDatabase: boolean;
}

/** Payload for creating or updating a connection, including plain-text secrets. */
export interface SaveConnectionRequest {
    /** Identifier, absent when creating. */
    _id?: ObjectId;

    /** User-supplied display name. */
    name: string;

    /** Which authentication mechanism this connection uses. */
    strategyKind: ConnectionStrategyKind;

    /** Guard rail preventing every write through this connection. */
    isReadOnly: boolean;

    /** Optional free-text note. */
    notes?: string;

    /** Colour token used to tint the interface. */
    colorTag?: string;

    /** Strategy-specific configuration, without secrets. */
    config: ConnectionConfig;

    /**
     * Plain-text secret to store, encrypted at rest. Omit to leave an existing
     * secret untouched; pass an empty string to clear it.
     */
    secret?: string;
}
