/**
 * Copies the server's shared-models folder to the client.
 *
 * Purpose: the server is the source of truth for every shared interface; the client
 * gets a verbatim copy. Run this after changing anything under
 * mongo-explorer-server/src/model/shared-models/.
 *
 * Inputs: none. Run from the workspace root or anywhere — paths are resolved
 * relative to this file.
 * Setup: none. Uses only Node built-ins.
 *
 * Usage: npx ts-node scripts/sync-shared-models.ts [--check]
 *   --check  Reports differences and exits non-zero instead of copying. For CI.
 */

import fs from 'fs';
import path from 'path';

/**
 * Finds the workspace root by walking up for the .code-workspace file. Avoids
 * __dirname and import.meta so the script runs the same whether Node loads it as
 * CommonJS or as an ES module.
 */
function findWorkspaceRoot(): string {
    let current = process.cwd();

    for (let depth = 0; depth < 8; depth += 1) {
        if (fs.existsSync(path.join(current, 'mongo-explorer.code-workspace'))) {
            return current;
        }

        const parent = path.dirname(current);

        if (parent === current) {
            break;
        }

        current = parent;
    }

    throw new Error('Could not locate mongo-explorer.code-workspace above the current directory.');
}

const workspaceRoot = findWorkspaceRoot();
const source = path.join(workspaceRoot, 'mongo-explorer-server', 'src', 'model', 'shared-models');
const destination = path.join(workspaceRoot, 'mongo-explorer-client', 'src', 'model', 'shared-models');

/** Header prepended to every copied file, so nobody edits the copy by mistake. */
const banner =
    '/* AUTO-COPIED FROM THE SERVER. Do not edit this file in the client project.\n' +
    '   Change it in mongo-explorer-server/src/model/shared-models/ and run\n' +
    '   scripts/sync-shared-models.ts. */\n\n';

/** Collects every TypeScript file under a directory, relative to it. */
function collectRelativeFiles(root: string, current = root): string[] {
    const found: string[] = [];

    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
        const full = path.join(current, entry.name);

        if (entry.isDirectory()) {
            found.push(...collectRelativeFiles(root, full));
        } else if (entry.name.endsWith('.ts')) {
            found.push(path.relative(root, full));
        }
    }

    return found;
}

/** Reads a source file and applies the banner. */
function readWithBanner(relative: string): string {
    return banner + fs.readFileSync(path.join(source, relative), 'utf-8');
}

/** Copies every shared model to the client. */
function copyAll(files: string[]): void {
    for (const relative of files) {
        const target = path.join(destination, relative);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.writeFileSync(target, readWithBanner(relative), 'utf-8');
    }

    console.log(`Copied ${files.length} shared model file(s) to the client.`);
}

/** Reports files that differ or are missing, without changing anything. */
function checkAll(files: string[]): void {
    const problems: string[] = [];

    for (const relative of files) {
        const target = path.join(destination, relative);

        if (!fs.existsSync(target)) {
            problems.push(`missing: ${relative}`);
            continue;
        }

        if (fs.readFileSync(target, 'utf-8') !== readWithBanner(relative)) {
            problems.push(`differs: ${relative}`);
        }
    }

    /* Files present on the client but absent on the server are also drift. */
    if (fs.existsSync(destination)) {
        const clientFiles = new Set(collectRelativeFiles(destination));

        for (const relative of clientFiles) {
            if (!files.includes(relative)) {
                problems.push(`orphaned on the client: ${relative}`);
            }
        }
    }

    if (!problems.length) {
        console.log(`Shared models are in sync: ${files.length} file(s).`);
        return;
    }

    console.error('Shared models have drifted:\n');
    problems.forEach(problem => console.error(`  ${problem}`));
    console.error('\nRun: npx ts-node scripts/sync-shared-models.ts');
    process.exit(1);
}

function main(): void {
    if (!fs.existsSync(source)) {
        console.error(`Cannot find the server's shared models at ${source}.`);
        process.exit(1);
    }

    const files = collectRelativeFiles(source);

    if (process.argv.includes('--check')) {
        checkAll(files);
        return;
    }

    copyAll(files);
}

main();
